"use client";
import { useState } from "react";
import { Download, Loader2, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
type Profile = { full_name?: string; headline?: string; location?: string; phone?: string; links?: Record<string, string>; preferences?: Record<string, any> };
const csv = (value: FormDataEntryValue | null) => String(value || "").split(",").map((x) => x.trim()).filter(Boolean);
export function SettingsForm({ initial }: { initial: Profile | null }) {
  const [busy, setBusy] = useState(false); const [profile, setProfile] = useState<Profile>(initial || {}); const [confirmation, setConfirmation] = useState(""); const p = profile.preferences || {};
  async function save(form: FormData): Promise<void> { setBusy(true); const body = { full_name: form.get("full_name"), headline: form.get("headline"), location: form.get("location"), phone: form.get("phone"), links: { linkedin: form.get("linkedin"), portfolio: form.get("portfolio") }, preferences: { target_roles: csv(form.get("target_roles")), locations: csv(form.get("locations")), min_salary: Number(form.get("min_salary") || 0) || undefined, industries: csv(form.get("industries")), must_haves: csv(form.get("must_haves")), work_mode: form.get("work_mode"), reminder_emails: Boolean(form.get("reminder_emails")), job_alert_emails: Boolean(form.get("job_alert_emails")) } }; const response = await fetch("/api/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const json = await response.json(); setBusy(false); if (!response.ok) { toast.error(json.error); return; } setProfile(json.profile); toast.success("Settings saved."); }
  async function loadSample() { setBusy(true); const response = await fetch("/api/sample-data", { method: "POST" }); const json = await response.json(); setBusy(false); if (!response.ok) { toast.error(json.error); return; } toast.success(json.existing ? "You already have data — sample data was not added." : "Sample data loaded."); }
  async function exportData() { const response = await fetch("/api/export"); if (!response.ok) { toast.error("Could not prepare export."); return; } const href = URL.createObjectURL(await response.blob()); const link = document.createElement("a"); link.href = href; link.download = "applied-data-export.zip"; link.click(); URL.revokeObjectURL(href); }
  async function remove() { if (confirmation !== "DELETE MY ACCOUNT") { toast.error("Type the confirmation exactly."); return; } const response = await fetch("/api/account/delete", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ confirmation }) }); const json = await response.json(); if (!response.ok) { toast.error(json.error); return; } location.assign("/signup"); }
  return <div className="space-y-6"><Card><CardHeader><CardTitle>Your profile & preferences</CardTitle></CardHeader><CardContent><form onSubmit={(e) => { e.preventDefault(); void save(new FormData(e.currentTarget)); }} className="grid gap-4 md:grid-cols-2"><Field name="full_name" label="Full name" value={profile.full_name} /><Field name="headline" label="Headline" value={profile.headline} placeholder="e.g. AI Product & Strategy" /><Field name="location" label="Location" value={profile.location} /><Field name="phone" label="Phone" value={profile.phone} /><Field name="linkedin" label="LinkedIn" value={profile.links?.linkedin} /><Field name="portfolio" label="Portfolio / website" value={profile.links?.portfolio} /><Field name="target_roles" label="Target roles" value={p.target_roles?.join(", ")} placeholder="Product Manager, Strategy" /><Field name="locations" label="Locations" value={p.locations?.join(", ") || "London"} /><Field name="min_salary" label="Minimum salary (GBP)" value={p.min_salary} type="number" /><Field name="industries" label="Industries" value={p.industries?.join(", ")} placeholder="Fintech, AI" /><Field name="must_haves" label="Must-haves" value={p.must_haves?.join(", ")} /><Field name="work_mode" label="Work mode" value={p.work_mode} placeholder="Hybrid" /><div className="md:col-span-2 flex gap-5 text-sm"><label><input type="checkbox" name="reminder_emails" defaultChecked={p.reminder_emails !== false} className="mr-2 accent-indigo-600" />Follow-up reminders</label><label><input type="checkbox" name="job_alert_emails" defaultChecked={p.job_alert_emails !== false} className="mr-2 accent-indigo-600" />Job alerts</label></div><Button className="md:col-span-2 w-fit" disabled={busy}>{busy && <Loader2 className="size-4 animate-spin" />}Save preferences</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Fictional demo data</CardTitle></CardHeader><CardContent><p className="text-sm text-slate-500">Add clearly fictional profiles, jobs, an application kit, and company leads for interface testing. None of it is based on you or safe to reuse in an application.</p><Button className="mt-4" variant="outline" onClick={() => void loadSample()} disabled={busy}>Load fictional demo data</Button></CardContent></Card><Card><CardHeader><CardTitle>Your data</CardTitle></CardHeader><CardContent><Button variant="outline" onClick={() => void exportData()}><Download className="size-4" />Export all data</Button><div className="mt-7 border-t pt-6"><h3 className="font-medium text-red-700">Delete account and data</h3><p className="mt-1 text-sm text-slate-500">This permanently deletes your account, applications, and uploaded CV files.</p><div className="mt-3 flex max-w-xl gap-2"><Input value={confirmation} onChange={(e) => setConfirmation(e.target.value)} placeholder="Type DELETE MY ACCOUNT" /><Button variant="destructive" onClick={() => void remove()}><Trash2 className="size-4" />Delete</Button></div></div></CardContent></Card></div>;
}
function Field({ name, label, value, placeholder, type = "text" }: { name: string; label: string; value?: string | number; placeholder?: string; type?: string }) { return <div><Label htmlFor={name}>{label}</Label><Input id={name} name={name} defaultValue={value || ""} placeholder={placeholder} type={type} /></div>; }
